CREATE DATABASE Exercicio1_1;

USE Exercicio1_1;

CREATE TABLE Pessoa(
	IdPessoa	INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50),
	CNH VARCHAR(20)
);


CREATE TABLE Telefone(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	NumeroTelefone VARCHAR(20)
);

CREATE TABLE Email(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	NomeEmail VARCHAR(50)
);

